#
# Documentation:
# https://yamllint.readthedocs.io/en/stable/
#

ignore: |
  .gitlab-ci.yml
  .markdownlint.yaml
  .yamllint.yaml
  frontend/ui/node_modules/

rules:
  brackets:
    forbid: false
    min-spaces-inside: 0
    max-spaces-inside: 2
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0
  indentation:
    spaces: 2
    indent-sequences: false
  key-ordering: disable
  line-length:
    max: 360
